name: Build APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    # نصب ابزارهای حیاتی که در سرورهای گیت‌هاب نیستند
    # وجود nasm و ninja برای بیلد شدن OpenSSL با NDK 27 ضروری است
    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build nasm pkg-config build-essential clang

    # برگشت به نسخه 27.2 که پروژه درخواست کرده است
    - name: Install NDK
      run: |
        yes | sdkmanager --install "ndk;27.2.12479018"
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/27.2.12479018" >> $GITHUB_ENV

    - name: Install Rust Targets
      run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

    - name: Grant execute permission
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/debug/*.ap
